# This file was generated by GoReleaser. DO NOT EDIT.
cask "netherchat" do
  version "0.8.0"

  on_macos do
    on_intel do
      sha256 "81e9f351c1b0b737ac3673bc525685cf8f513625e64427af4859811b98922969"
      url "https://github.com/salehkreiner/netherchat/releases/download/v#{version}/netherchat_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "858fa62f35bb768313cfdda8416f72dad1773639539424296a0845c02c6cc124"
      url "https://github.com/salehkreiner/netherchat/releases/download/v#{version}/netherchat_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "08eefa84a25a6da363340c48f614724e6f570b1109217ff8ce0e0a081a3c2e27"
      url "https://github.com/salehkreiner/netherchat/releases/download/v#{version}/netherchat_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "0080b52941562ee7416a6dc1d0c6830cc00591b2ef0fb41fe066daf425ca564f"
      url "https://github.com/salehkreiner/netherchat/releases/download/v#{version}/netherchat_linux_arm64.tar.gz"
    end
  end

  name "netherchat"
  desc "Self-hostable, end-to-end encrypted messaging for terminals and browsers. A blind relay that cannot read your messages — proven by the build graph, not a promise."
  homepage "https://netherchat.com"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "netherchat"

  # No zap stanza required

end
