# This file was generated by GoReleaser. DO NOT EDIT.
cask "netherchat" do
  version "0.4.0"

  on_macos do
    on_intel do
      sha256 "318c734e1a114f3de02a0885b624c8540b121181132ea64ce2111391cbe0a229"
      url "https://github.com/salehkreiner/netherchat/releases/download/v#{version}/netherchat_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "fe9c0c95aa5124d10b8b1ee07af3b1172f48237d04c1222f7047493929538b1d"
      url "https://github.com/salehkreiner/netherchat/releases/download/v#{version}/netherchat_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "08b06a407005306e157befd4bf02b14de2078f27d82aa8d7a1caa47b9b7488c8"
      url "https://github.com/salehkreiner/netherchat/releases/download/v#{version}/netherchat_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "44a5683422d8155a85d47dbc7db266ef58db2580d9f509691e44dfb4b35dc6fd"
      url "https://github.com/salehkreiner/netherchat/releases/download/v#{version}/netherchat_linux_arm64.tar.gz"
    end
  end

  name "netherchat"
  desc "Self-hostable, end-to-end encrypted messaging for terminals and browsers. A blind relay that cannot read your messages — proven by the build graph, not a promise."
  homepage "https://netherchat.com"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "netherchat"

  # No zap stanza required

end
