# This file was generated by GoReleaser. DO NOT EDIT.
cask "netherchat" do
  version "1.0.0"

  on_macos do
    on_intel do
      sha256 "7d608dd8791c062ced3d608b99517c580a4adee74982c9809cfa9f5558506f56"
      url "https://github.com/salehkreiner/netherchat/releases/download/v#{version}/netherchat_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "39343995a7671ba5b51ca422a5d37989ed434548fff75534b5ff4b1c8459a857"
      url "https://github.com/salehkreiner/netherchat/releases/download/v#{version}/netherchat_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "545ce8851ed98e0a3cab63be9e14fefb4afda7a9e0681186bfa1d5afd2213829"
      url "https://github.com/salehkreiner/netherchat/releases/download/v#{version}/netherchat_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "00a60ea4f12cf6d9c451628327cb578bc596595891af3633f5c7725c14a624c9"
      url "https://github.com/salehkreiner/netherchat/releases/download/v#{version}/netherchat_linux_arm64.tar.gz"
    end
  end

  name "netherchat"
  desc "Self-hostable, end-to-end encrypted messaging for terminals and browsers. A blind relay that cannot read your messages — proven by the build graph, not a promise."
  homepage "https://netherchat.com"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "netherchat"

  # No zap stanza required

end
